#!/bin/bash

HELPM="\n bash script to collect stats from ipyrad assemblies generated by the scripts 1_run_iCT.sh and 3_run_bCT.sh \n
Usage: harvest_stats.sh -s <steps to harvest> -w <assemblies dir> -o <output dir> \n
Arguments: \n
-s: ipyrad's steps from which to harvest the stats. Can be either 3, 5 or 7 or any combination of the three. Exemple: -s 357 \n
-i: directory where stats files are stored \n
-h: print this message and exit \n"

if [[ $# -eq 0 ]]
then
echo -e $HELPM
exit 1
fi

while [[ $# -gt 0 ]]
do
key="$1"

case "$key" in
	-s | --steps)
	STEPS=$2
	shift
	shift
	;;
	-i | --indir)
	INDIR=$2
	shift
	shift
	;;
	-h | --help)
	echo -e $HELPM
	exit 1
	shift
	shift
	;;
esac
done

STEP3=$(echo $STEPS | grep 3)
STEP5=$(echo $STEPS | grep 5)
STEP7=$(echo $STEPS | grep 7)

if [ -n "$STEP3" ]
then

echo "Harvesting statistics from s3" 

cd ${INDIR}

# this part formate and concatenate all the s3 files in a table easily readable by R
# store the header in a variable
header=$(head -1 $(ls s3* | head -1))
# write this header (+ 2 additional fields) in a file that will contain the concatenated table
echo "sample"$header" threshold" > all_s3.txt
# iterate on each file
for i in s3*
do
# find the CT and store it in a variable
t=$(echo $i | sed 's/s3_//' | sed 's/.txt//')
# open the file and execute the following actions : change the fields delimiter to 1 space; add a new field with the CT; remove the first line (header); add a newline character at the end of the last line (originally absent) and then write the result in the big table file
cat $i | sed -E 's/[[:space:]]+/ /g' | sed "s/$/ $t/" | sed '1d'  | sed "$ s/$/\n/" >> all_s3.txt
done

cd ..

fi

if [ -n "$STEP5" ]
then

echo "Harvesting statistics from s5"

cd ${INDIR}

header=$(head -1 $(ls s5* | head -1))
echo "sample"$header" threshold" > all_s5.txt
for i in s5*
do
t=$(echo $i | cut -d'.' -f1 | cut -d'_' -f2)
cat $i | sed -E 's/[[:space:]]+/ /g' | sed "s/$/ $t/" | sed '1d'  | sed "$ s/$/\n/" >> all_s5.txt
done

cd ..
fi

if [ -n "$STEP7" ]
then

echo "Harvesting statistics from s7"

cd ${INDIR}

head -1 $(ls *loci.txt | head -1) > loci_all_CT.txt
sed -i 's/$/ threshold/' loci_all_CT.txt
sed -i 's/^/N_samples/' loci_all_CT.txt
sed -i 's/^[[:space:]]*//' loci_all_CT.txt

for i in *loci.txt
do
t=$(echo $i | rev | cut -d'/' -f1 | rev | cut -d'_' -f1)
cat $i | sed '1d' | sed "s/$/ $t/" >> loci_all_CT.txt
done

sed -i -r "s/[[:space:]]+/ /g" loci_all_CT.txt

head -1 $(ls *var.txt | head -1) > var_all_CT.txt
sed -i 's/^/N/' var_all_CT.txt
sed -i 's/$/ threshold/' var_all_CT.txt
sed -i 's/^[[:space:]]*//' var_all_CT.txt

for i in *var.txt
do
t=$(echo $i | rev | cut -d'/' -f1 | rev | cut -d'_' -f1)
cat $i | sed '1d' | sed "s/$/ $t/" >> var_all_CT.txt
done

sed -E -i 's/[[:space:]]+/ /g' var_all_CT.txt

cd ..
fi

echo -e "\n the stats files are in ${INDIR}\n"
